### PR TITLE
Add SPANISH (ESPAÑOL) Language Support

### PR DESCRIPTION
**Pull request by rbenitezpagan**
This is an enhancement or feature.

## Summary

This PR adds SPANISH (Español) Language Support to the theme.

## Context

This work addresses this [**Feature Request**](https://github.com/raviriley/agency-jekyll-theme/issues/2)

## Changes

- _config.yml include variable `locale` -> `locale: "en-US" # See available languages in _data/sitetext.yml`
- _data/sitetext.yml define variables for English `US, CA, GB, AU` and Spanish (Español) `ES, CO`
- _data/sitetext.yml translate content to Spanish
- _data/navigation.yml define variables for English `US, CA, GB, AU` and Spanish (Español) `ES, CO`
- _data/navigation.yml translate content to Spanish
-  _includes/about.html, _includes/clients.html, _includes/contact.html, _includes/footer.html, _includes/modals.html, _includes/portfolio_grid.html, _includes/services.html, _includes/team.html, _includes/timeline.html change variable from `site.data.sitetext.` to `site.data.sitetext[site.locale].`
- _includes/nav.html and _includes/navheader.html change variable from `site.data.navigation.nav` to `site.data.navigation[site.locale].nav`
- _layouts/default.html change `<html>` to `<html lang="{{ site.locale | slice: 0,2 | default: "en" }}">`

### CODE REVIEW

**Comment by raviriley** [comment]
Looks good! 

#2

**Review by raviriley — COMMENTED** [review]
For `_layouts/default.html` why is `slice: 0,2` in the default layout?

**Comment by rbenitezpagan** [comment]
@raviriley I followed the referenced sourced. See (https://github.com/mmistakes/minimal-mistakes/blob/641ca6f3d8cd8fb0ae24e4f77b2e62a44a65e53b/_layouts/default.html#L11)

I believe having `en` or `es` helps with the page's SEO. It is a configurable variable to specify the language of the element's content. See (https://www.w3schools.com/tags/att_global_lang.asp)

**Comment by raviriley** [comment]
Got it! Thanks for your PR!

**Pull request merged**
